-- =====================================================
-- 01 tables  |  SIGPOA
-- Solo estructura y claves primarias (las demás restricciones van en los archivos 02-04)
-- Se puede volver a ejecutar: elimina y recrea las tablas.
-- =====================================================

DROP TABLE IF EXISTS propuestas_participativas CASCADE;
DROP TABLE IF EXISTS contrataciones            CASCADE;
DROP TABLE IF EXISTS gastos                    CASCADE;
DROP TABLE IF EXISTS actividades               CASCADE;
DROP TABLE IF EXISTS proveedores               CASCADE;
DROP TABLE IF EXISTS organizaciones            CASCADE;
DROP TABLE IF EXISTS partidas                  CASCADE;
DROP TABLE IF EXISTS gestiones                 CASCADE;
DROP TABLE IF EXISTS usuarios                  CASCADE;
DROP TABLE IF EXISTS unidades                  CASCADE;
DROP TABLE IF EXISTS entidades                 CASCADE;
DROP TABLE IF EXISTS roles                     CASCADE;

-- ---------- Seguridad ----------
CREATE TABLE roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(30)  NOT NULL,
    descripcion  VARCHAR(150),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------- Estructura institucional ----------
CREATE TABLE entidades (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(150) NOT NULL,
    tipo          VARCHAR(30)  NOT NULL,
    departamento  VARCHAR(50)  NOT NULL,
    municipio     VARCHAR(80),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE unidades (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_id   BIGINT       NOT NULL,
    nombre       VARCHAR(120) NOT NULL,
    responsable  VARCHAR(120),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(120) NOT NULL,
    email          VARCHAR(120) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    rol_id         BIGINT       NOT NULL,
    unidad_id      BIGINT,
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------- Planificación y ejecución ----------
CREATE TABLE gestiones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio        SMALLINT    NOT NULL,
    estado      VARCHAR(10) NOT NULL DEFAULT 'abierta',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE partidas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(10)  NOT NULL,
    nombre      VARCHAR(120) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------- Organizaciones y proveedores ----------
CREATE TABLE organizaciones (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(150) NOT NULL,
    tipo                VARCHAR(30)  NOT NULL,
    personeria_juridica VARCHAR(50),
    representante       VARCHAR(120),
    telefono            VARCHAR(20),
    direccion           VARCHAR(200),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE proveedores (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(150) NOT NULL,
    nit         VARCHAR(20),
    telefono    VARCHAR(20),
    direccion   VARCHAR(200),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE actividades (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gestion_id        BIGINT        NOT NULL,
    unidad_id         BIGINT        NOT NULL,
    partida_id        BIGINT        NOT NULL,
    organizacion_id   BIGINT,
    objetivo          VARCHAR(200)  NOT NULL,
    meta              VARCHAR(200),
    descripcion       TEXT,
    monto_programado  NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE gastos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actividad_id    BIGINT        NOT NULL,
    proveedor_id    BIGINT,
    fecha           DATE          NOT NULL DEFAULT CURRENT_DATE,
    monto           NUMERIC(14,2) NOT NULL,
    detalle         VARCHAR(250),
    registrado_por  BIGINT        NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE contrataciones (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actividad_id    BIGINT        NOT NULL,
    proveedor_id    BIGINT        NOT NULL,
    descripcion     VARCHAR(250)  NOT NULL,
    monto_cotizado  NUMERIC(14,2) NOT NULL DEFAULT 0,
    estado           VARCHAR(15)  NOT NULL DEFAULT 'solicitud',
    fecha            DATE         NOT NULL DEFAULT CURRENT_DATE,
    fecha_cotizacion DATE,
    fecha_adjudicacion DATE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE propuestas_participativas (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  BIGINT        NOT NULL,
    gestion_id       BIGINT        NOT NULL,
    actividad_id     BIGINT,
    titulo           VARCHAR(200)  NOT NULL,
    descripcion      TEXT,
    monto_asignado   NUMERIC(14,2) NOT NULL DEFAULT 0,
    estado           VARCHAR(15)   NOT NULL DEFAULT 'propuesto',
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);
